name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          image_name: docker-build

      - name: Build docker image
        uses: ./.github/actions/docker

      - name: Build target_lo in docker
        uses: ./.github/actions/docker
        with:
          run: make -C target_lo

      - name: Build target_f1 in docker
        uses: ./.github/actions/docker
        with:
          run: make -C target_f1
