name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: docker-cache-${{ hashFiles('docker/**') }}-{hash}
          restore-keys: docker-cache-${{ hashFiles('docker/**') }}-
      - name: Build docker image
        uses: ./.github/actions/docker

      - name: Check syntax
        uses: ./.github/actions/docker
        continue-on-error: true
        with:
          run: /syntax_check.sh

      - name: Build target_lo in docker
        uses: ./.github/actions/docker
        with:
          run: make -C target_lo

      - name: Build target_f1 in docker
        uses: ./.github/actions/docker
        with:
          run: make -C target_f1
