name: 'Reindex'

on:
  release:
    types: [prereleased,released]

jobs:
  reindex:
    name: 'Reindex updates'
    runs-on: [self-hosted,FlipperZeroK8s]
    steps:
      - name: Trigger reindex
        run: |
          curl -X POST -F 'key=${{ secrets.REINDEX_KEY }}' ${{ secrets.REINDEX_URL }}
